package com.melek.javaproject.models;

public enum Categories {

	HEALTHCARE,
    EDUCATION,
    POVERTY_ALLEVIATION,
    ENVIRONMENT,
    ANIMAL_WELFARE,
    CHILD_WELFARE,
    DISASTER_RELIEF,
    ARTS_AND_CULTURE,
    HUMAN_RIGHTS,
    COMMUNITY_DEVELOPMENT,
    ELDERLY_SUPPORT,
    FOOD_SECURITY,
    WOMEN_EMPOWERMENT,
    YOUTH_PROGRAMS,
    HOUSING,
    RELIGIOUS,
    LGBTQ_RIGHTS
}
